name: PR Version Check

on:
  pull_request:
    branches: [ main ]

jobs:
  version-check:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check App Version
      run: |
        VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" YourApp/Info.plist)
        echo "App Version is $VERSION"
